#!/usr/bin/env python3
'''
Simple example calling an arbitrary action in a loop.
'''

import common.Api_pb2 as hudiy_api
from common.Client import Client, ClientEventHandler
# import serial
# import subprocess
import threading
# from collections import deque
import time


class EventHandler(ClientEventHandler):
    '''Event handler for events generated by hudiy'''
    def on_hello_response(self, client, message):
        print(
            "received hello response, result: {}, app version: {}.{}, api version: {}.{}"
            .format(message.result, message.app_version.major,
                    message.app_version.minor, message.api_version.major,
                    message.api_version.minor))

        set_status_subscriptions = hudiy_api.SetStatusSubscriptions()
        set_status_subscriptions.subscriptions.append(
                hudiy_api.SetStatusSubscriptions.Subscription.MEDIA)
        client.send(hudiy_api.MESSAGE_SET_STATUS_SUBSCRIPTIONS,
                0, set_status_subscriptions.SerializeToString())


def trigger_action(client, actionstr):
    '''Trigger action like next song, volume up etc...'''
    try:
        dispatch_action = hudiy_api.DispatchAction()
        dispatch_action.action = actionstr
        client.send(hudiy_api.MESSAGE_DISPATCH_ACTION,
                    0, dispatch_action.SerializeToString())
    except Exception as e:
        print(f"[ERROR] Failed to trigger action {actionstr}: {e}")


def hudiy_listener(client):
    '''Must be here, otherwise connection is broken after few moments'''
    print("[INFO] HUDIY listener started")
    while True:
        try:
            client.wait_for_message()
        except Exception as e:
            print(f"[ERROR] HUDIY listener failed: {e}")
            break


def main():
    '''Main function'''
    # Connection to hudiy
    client = Client("HUDIY Discovery II")
    event_handler = EventHandler()
    client.set_event_handler(event_handler)
    client.connect('127.0.0.1', 44406, use_websocket=True)

    threading.Thread(target=hudiy_listener, args=(client,), daemon=True).start()

    while True:
        print("[INFO] Main loop tick")
        # trigger volume up
        trigger_action(client, "output_volume_up")

        time.sleep(5)

    client.disconnect()


if __name__ == "__main__":
    main()