#!/usr/bin/env python3
'''
Simple example calling an arbitrary action in a loop.
'''

import common.Api_pb2 as hudiy_api
from common.Client import Client, ClientEventHandler
# import serial
# import subprocess
import threading
# from collections import deque
import time
from gpiozero import Button
from signal import pause
import subprocess as sp

sp.call(['sudo', 'modprobe', 'uinput'])
sp.call(['sudo', 'chown', 'dan', '/dev/uinput'])

BL_PATH = '/sys/class/backlight/11-0045'
BUTTONS_PINS = [6, 19, 13, 20, 21, 16, 26]
BUTTONS = [Button(p, pull_up=True, bounce_time=0.05) for p in BUTTONS_PINS]
NAMES = ['play', 'esc', 'mute', 'br_up', 'br_dn', 'vl_up', 'vl_dn']
HU_ACTIONS = ['now_playing_toggle_play',
              'equalizer_preset_settings',
              'go_back',
              'display_brightness_up',
              'display_brightness_down',
              'output_volume_up',
              'output_volume_down']


def get_press_func(pin, name, client, actionstr):
    '''Generate on_press function for button'''
    if actionstr == 'display_brightness_up':
        def on_press():
            print("pressed:", pin, name, actionstr)
            change_brightness(up=True)
    elif actionstr == 'display_brightness_down':
        def on_press():
            print("pressed:", pin, name, actionstr)
            change_brightness(up=False)
    else:
        def on_press():
            print("pressed:", pin, name, actionstr)
            trigger_action(client, actionstr)

    return on_press


def change_brightness(up=True):
    '''Does not use hudiy.  Change the system brigntness directly'''
    max_file = f'{BL_PATH}/max_brightness'
    with open(max_file, 'r', encoding='utf-8') as mf:
        max_brightness = int(mf.read().strip())
    set_file = f'{BL_PATH}/brightness'
    with open(set_file, 'r', encoding='utf-8') as sf:
        cur_brightness = int(sf.read().strip())
    step = 3

    if up:
        new_brightness = min(max_brightness, cur_brightness + step)
    else:
        new_brightness = max(0, cur_brightness - step)
    with open(set_file, 'w', encoding='utf-8') as sf:
        sf.write(str(new_brightness))
    print(f"[INFO] Brightness changed from {cur_brightness} to {new_brightness}")


class EventHandler(ClientEventHandler):
    '''Event handler for events generated by hudiy'''
    def on_hello_response(self, client, message):
        print(
            "received hello response, result: {}, app version: {}.{}, api version: {}.{}"
            .format(message.result, message.app_version.major,
                    message.app_version.minor, message.api_version.major,
                    message.api_version.minor))

        set_status_subscriptions = hudiy_api.SetStatusSubscriptions()
        set_status_subscriptions.subscriptions.append(
                hudiy_api.SetStatusSubscriptions.Subscription.MEDIA)
        client.send(hudiy_api.MESSAGE_SET_STATUS_SUBSCRIPTIONS,
                0, set_status_subscriptions.SerializeToString())


def trigger_action(client, actionstr):
    '''Trigger action like next song, volume up etc...'''
    try:
        dispatch_action = hudiy_api.DispatchAction()
        dispatch_action.action = actionstr
        client.send(hudiy_api.MESSAGE_DISPATCH_ACTION,
                    0, dispatch_action.SerializeToString())
    except Exception as e:
        print(f"[ERROR] Failed to trigger action {actionstr}: {e}")


def hudiy_listener(client):
    '''Must be here, otherwise connection is broken after few moments'''
    print("[INFO] HUDIY listener started")
    while True:
        try:
            client.wait_for_message()
        except Exception as e:
            print(f"[ERROR] HUDIY listener failed: {e}")
            break


def main():
    '''Main function'''
    # Connection to hudiy
    client = Client("HUDIY Discovery II")
    event_handler = EventHandler()
    client.set_event_handler(event_handler)
    client.connect('127.0.0.1', 44406, use_websocket=True)

    threading.Thread(target=hudiy_listener, args=(client,), daemon=True).start()

    for pin, butt, name, action in zip(BUTTONS_PINS, BUTTONS, NAMES, HU_ACTIONS):
        butt.when_pressed = get_press_func(pin, name, client, action)

    print("Waiting for button presses...")
    pause()
    # while True:
    #     print("[INFO] Main loop tick")
    #     # trigger volume up
    #     trigger_action(client, "output_volume_up")

    #     time.sleep(5)

    # client.disconnect()


if __name__ == "__main__":
    main()